python main.py \
--base_model="n2v" \
--loss_func="sg_aug" \
--test_set="valid" \
--n_negative=4 \
--lr=0.1 \
--lam=0.01 \
--seed=2020 \
--dataset="ogbl-citation2" \
--recdim=128 \
--batch_size=128 \
--epochs 25